SpicyX/Areas/Admin/Controllers/PostionController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SpicyX.Areas.Admin.ViewModels.Position;
using SpicyX.DAL;
using SpicyX.Models;

namespace SpicyX.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class PostionController : Controller
    {
        private readonly AppDbContext _db;
        public PostionController(AppDbContext db)
        {
            _db = db;
        }
        public async Task<IActionResult> Index()
        {
            List<Position> positions = await _db.Positions.Include(x=>x.Chefs).ToListAsync();
            return View(positions);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(CreatePositionVM create)
        {
            if(!ModelState.IsValid) return View(create);

            bool result = await _db.Positions.AnyAsync(x=>x.Name.Trim().ToLower()==create.Name.Trim().ToLower());
            if(result)
            {
                ModelState.AddModelError("Name","is exists");
                return View(create);
            }
            Position position = new Position { Name = create.Name };
            
            await _db.Positions.AddAsync(position);
            await _db.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Update(int id)
        {
            if(id<=0) return BadRequest();
            Position position= await _db.Positions.FirstOrDefaultAsync(x=>x.Id==id);
            if (position == null) return NotFound();

            UpdatePositionVM update = new UpdatePositionVM
            {
                Name = position.Name,
            };
            return View(update);
        }
        [HttpPost]
        public async Task<IActionResult> Update(int id,UpdatePositionVM update)
        {
            if (!ModelState.IsValid) return View(update);
            Position position = await _db.Positions.FirstOrDefaultAsync(x => x.Id == id);
            if(position==null) return NotFound();

            bool result = await _db.Positions.AnyAsync(x=>x.Name.Trim().ToLower()==update.Name.Trim().ToLower() && x.Id==id);
            if(result)
            {
                ModelState.AddModelError("Name","is exists");
                return View(update);
            }
            position.Name = update.Name;

            await _db.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int id)
        {
            if (id <= 0) return BadRequest();
            Position position = await _db.Positions.FirstOrDefaultAsync(x=>x.Id==id);
            if(position==null) return NotFound();

            _db.Positions.Remove(position);
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

SpicyX/Areas/Admin/Views/Postion/Create.cshtml
@using SpicyX.Areas.Admin.ViewModels.Position
@model CreatePositionVM

<div class="col-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Create Position</h4>
            <form class="forms-sample" method="post">
                
                <div class="form-group">
                    <label asp-for="Name">Name</label>
                    <input asp-for="Name" type="text" class="form-control" placeholder="Name">
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>

                <button type="submit" class="btn btn-primary me-2">Submit</button>
                <button asp-action="Index" asp-controller="Position" class="btn btn-light">Cancel</button>
            </form>
        </div>
    </div>
</div>

SpicyX/Areas/Admin/Views/Postion/Index.cshtml
@model List<Position> 
@{
    int count = 0;
}

<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Position Table</h4>

            <a asp-action="Create" asp-controller="Postion" class="btn btn-success">Create Position</a>

            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>
                                No
                            </th>
                            <th>
                                Name
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (Position position in Model)
                        {
                            count++;
                            <tr>
                                <td>
                                    @count
                                </td>
                                <td>
                                    @position.Name
                                </td>
                                <td>
                                    <a asp-action="Update" asp-controller="Postion" asp-route-id="@position.Id" class="btn btn-primary"><i class="mdi mdi-grease-pencil"></i></a>
                                    <a asp-action="Delete" asp-controller="Postion" asp-route-id="@position.Id" class="btn btn-danger"><i class="mdi mdi-delete"></i></a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

SpicyX/Areas/Admin/Views/Postion/Update.cshtml
@using SpicyX.Areas.Admin.ViewModels.Position
@model UpdatePositionVM

<div class="col-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Update Position</h4>
            <form class="forms-sample" method="post" enctype="multipart/form-data">
                
                <div class="form-group">
                    <label asp-for="Name">Name</label>
                    <input asp-for="Name" type="text" class="form-control" placeholder="Name">
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                

                <button type="submit" class="btn btn-primary me-2">Submit</button>
                <button asp-action="Index" asp-controller="Position" class="btn btn-light">Cancel</button>
            </form>
        </div>
    </div>
</div>