SpicyX/Areas/Admin/Controllers/ChefController.cs
using Be.Areas.Admin.ViewModels;
using Be.Areas.Admin.ViewModels.Chef;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SpicyX.DAL;
using SpicyX.Models;
using SpicyX.Utilities.Extentions;

namespace SpicyX.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ChefController : Controller
    {
        private readonly AppDbContext _db;
        private readonly IWebHostEnvironment _env;
        public ChefController(AppDbContext db,IWebHostEnvironment env)
        {
            _db = db;
            _env = env;
        }
        public async Task<IActionResult> Index()
        {
            List<Chef> chefs =await _db.Chefs.Include(x=>x.Position).ToListAsync();
            return View(chefs);
        }

        public async Task<IActionResult> Create()
        {
            CreateChefVM create = new CreateChefVM
            {
                Positions= await _db.Positions.ToListAsync(),
            };
            return View(create);
        }
        [HttpPost]
        public async Task<IActionResult> Create(CreateChefVM create)
        {
            if (!ModelState.IsValid)
            {
                create.Positions= await _db.Positions.ToListAsync();
                return View(create);
            }
            bool result = await _db.Chefs.AnyAsync(x=>x.Name.Trim().ToLower()==create.Name.Trim().ToLower());
            if (result)
            {
                create.Positions = await _db.Positions.ToListAsync();
                ModelState.AddModelError("Name","is exist");
                return View(create);
            }
            if (!create.Photo.ValidateType())
            {
                create.Positions = await _db.Positions.ToListAsync();
                ModelState.AddModelError("Photo","not valid");
                return View(create);
            }
            if (!create.Photo.ValidateSize(10))
            {
                create.Positions=await _db.Positions.ToListAsync();
                ModelState.AddModelError("Photo","max 10mb");
                return View(create);
            }

            Chef chef = new Chef
            {
                Name = create.Name,
                Image = await create.Photo.CreateFile(_env.WebRootPath,"assets","img"),
                TwitLink= create.TwitLink,
                FaceLink= create.FaceLink,
                LinkedLink= create.LinkedLink,
                GoogleLink= create.GoogleLink,
                PositionId= create.PositionId,
            };
            await _db.Chefs.AddAsync(chef);
            await _db.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Update(int id)
        {
            if (id <= 0) return BadRequest();
            Chef chef=await _db.Chefs.FirstOrDefaultAsync(x=>x.Id == id);
            if(chef==null) return NotFound();

            UpdateChefVM update = new UpdateChefVM
            {
                Name= chef.Name,
                Image= chef.Image,
                PositionId= chef.PositionId,
                Positions=await _db.Positions.ToListAsync(),
                TwitLink = chef.TwitLink,
                FaceLink= chef.FaceLink,
                LinkedLink= chef.LinkedLink,
                GoogleLink= chef.GoogleLink,
            };
            return View(update);
        }
        [HttpPost]
        public async Task<IActionResult> Update(int id,UpdateChefVM update)
        {
            if(!ModelState.IsValid)
            {
                update.Positions = await _db.Positions.ToListAsync();
                return View(update);
            }
            Chef chef = await _db.Chefs.FirstOrDefaultAsync(x=> x.Id == id);
            if(chef==null) return NotFound();

            bool result = await _db.Chefs.AnyAsync(x=>x.Name.Trim().ToLower()==update.Name.Trim().ToLower() && x.Id!=id);
            if(result)
            {
                update.Positions= await _db.Positions.ToListAsync();
                ModelState.AddModelError("Name","is exists");
                return View(update);
            }
            if (update.Photo is not null)
            {
                if (!update.Photo.ValidateType())
                {
                    update.Positions = await _db.Positions.ToListAsync();
                    ModelState.AddModelError("Photo","not valid");
                    return View(update);
                }
                if (!update.Photo.ValidateSize(10))
                {
                    update.Positions = await _db.Positions.ToListAsync();
                    ModelState.AddModelError("Photo", "max 10mb");
                    return View(update);
                }
                chef.Image.DeleteFile(_env.WebRootPath,"assets","img");
                chef.Image = await update.Photo.CreateFile(_env.WebRootPath,"assets","img");
            }

            chef.Name= update.Name;
            chef.PositionId= update.PositionId;
            chef.TwitLink= update.TwitLink;
            chef.LinkedLink= update.LinkedLink;
            chef.GoogleLink= update.GoogleLink;
            chef.FaceLink= update.FaceLink;

            await _db.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int id)
        {
            if (id <= 0) return BadRequest();
            Chef chef = await _db.Chefs.FirstOrDefaultAsync(x=>x.Id==id);
            if (chef == null) return NotFound();
            
            _db.Chefs.Remove(chef);
            await _db.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
    }
}

SpicyX/Areas/Admin/Controllers/SettingsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SpicyX.Areas.Admin.ViewModels.Settings;
using SpicyX.DAL;
using SpicyX.Models;

namespace SpicyX.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class SettingsController : Controller
    {
        private readonly AppDbContext _db;
        public SettingsController(AppDbContext db)
        {
            _db = db;
        }
        public async Task<IActionResult> Index()
        {
            List<Settings> settings = await _db.Settings.ToListAsync();
            return View(settings);
        }

        public async Task<IActionResult> Update(int id)
        {
            if(id<=0) return BadRequest();
            Settings settings = await _db.Settings.FirstOrDefaultAsync(x => x.Id == id);
            if(settings==null) return NotFound();

            UpdateSettingsVM update = new UpdateSettingsVM { Key=settings.Key,Value=settings.Value };
            return View(update);
        }
        [HttpPost]
        public async Task<IActionResult> Update(int id,UpdateSettingsVM update)
        {
            if(!ModelState.IsValid) return View(update);
            Settings settings = await _db.Settings.FirstOrDefaultAsync(x=>x.Id == id);
            if(settings==null) return NotFound();

            bool result= await _db.Settings.AnyAsync(x=>x.Key.Trim().ToLower() == update.Key.ToLower() && x.Id!=id);
            if (result)
            {
                ModelState.AddModelError("Name","exists");
                return View(update);
            }
            settings.Key= update.Key;
            settings.Value=update.Value;

            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }


    }
}

SpicyX/Areas/Admin/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Majestic Admin</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="~/admin/vendors/mdi/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="~/admin/vendors/base/vendor.bundle.base.css">
    <!-- endinject -->
    <!-- plugin css for this page -->
    <link rel="stylesheet" href="~/admin/vendors/datatables.net-bs4/dataTables.bootstrap4.css">
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <link rel="stylesheet" href="~/admin/css/style.css">
    <!-- endinject -->
    <link rel="shortcut icon" href="~/admin/images/favicon.png" />
</head>
<body>
    <div class="container-scroller">
        <div class="row p-0 m-0 proBanner" id="proBanner">
            <div class="col-md-12 p-0 m-0">
                <div class="card-body card-body-padding d-flex align-items-center justify-content-between">
                    <div class="ps-lg-1">
                        <div class="d-flex align-items-center justify-content-between">
                            <p class="mb-0 font-weight-medium me-3 buy-now-text">Free 24/7 customer support, updates, and more with this template!</p>
                            <a href="https://www.bootstrapdash.com/product/majestic-admin-pro/?utm_source=organic&utm_medium=banner&utm_campaign=buynow_demo" target="_blank" class="btn me-2 buy-now-btn border-0">Get Pro</a>
                        </div>
                    </div>
                    <div class="d-flex align-items-center justify-content-between">
                        <a href="https://www.bootstrapdash.com/product/majestic-admin-pro/"><i class="mdi mdi-home me-3 text-white"></i></a>
                        <button id="bannerClose" class="btn border-0 p-0">
                            <i class="mdi mdi-close text-white me-0"></i>
                        </button>
                    </div>
                </div>
            </div>
        </div>
        <!-- partial:partials/_navbar.html -->
        <nav class="navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
            <div class="navbar-brand-wrapper d-flex justify-content-center">
                <div class="navbar-brand-inner-wrapper d-flex justify-content-between align-items-center w-100">
                    <a class="navbar-brand brand-logo" href="index.html"><img src="~/admin/images/logo.svg" alt="logo" /></a>
                    <a class="navbar-brand brand-logo-mini" href="index.html"><img src="~/admin/images/logo-mini.svg" alt="logo" /></a>
                    <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
                        <span class="mdi mdi-sort-variant"></span>
                    </button>
                </div>
            </div>
            <div class="navbar-menu-wrapper d-flex align-items-center justify-content-end">
                <ul class="navbar-nav mr-lg-4 w-100">
                    <li class="nav-item nav-search d-none d-lg-block w-100">
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text" id="search">
                                    <i class="mdi mdi-magnify"></i>
                                </span>
                            </div>
                            <input type="text" class="form-control" placeholder="Search now" aria-label="search" aria-describedby="search">
                        </div>
                    </li>
                </ul>
                <ul class="navbar-nav navbar-nav-right">
                    <li class="nav-item dropdown me-1">
                        <a class="nav-link count-indicator dropdown-toggle d-flex justify-content-center align-items-center" id="messageDropdown" href="#" data-bs-toggle="dropdown">
                            <i class="mdi mdi-message-text mx-0"></i>
                            <span class="count"></span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="messageDropdown">
                            <p class="mb-0 font-weight-normal float-left dropdown-header">Messages</p>
                            <a class="dropdown-item">
                                <div class="item-thumbnail">
                                    <img src="~/admin/images/faces/face4.jpg" alt="image" class="profile-pic">
                                </div>
                                <div class="item-content flex-grow">
                                    <h6 class="ellipsis font-weight-normal">
                                        David Grey
                                    </h6>
                                    <p class="font-weight-light small-text text-muted mb-0">
                                        The meeting is cancelled
                                    </p>
                                </div>
                            </a>
                            <a class="dropdown-item">
                                <div class="item-thumbnail">
                                    <img src="~/admin/images/faces/face2.jpg" alt="image" class="profile-pic">
                                </div>
                                <div class="item-content flex-grow">
                                    <h6 class="ellipsis font-weight-normal">
                                        Tim Cook
                                    </h6>
                                    <p class="font-weight-light small-text text-muted mb-0">
                                        New product launch
                                    </p>
                                </div>
                            </a>
                            <a class="dropdown-item">
                                <div class="item-thumbnail">
                                    <img src="~/admin/images/faces/face3.jpg" alt="image" class="profile-pic">
                                </div>
                                <div class="item-content flex-grow">
                                    <h6 class="ellipsis font-weight-normal">
                                        Johnson
                                    </h6>
                                    <p class="font-weight-light small-text text-muted mb-0">
                                        Upcoming board meeting
                                    </p>
                                </div>
                            </a>
                        </div>
                    </li>
                    <li class="nav-item dropdown me-4">
                        <a class="nav-link count-indicator dropdown-toggle d-flex align-items-center justify-content-center notification-dropdown" id="notificationDropdown" href="#" data-bs-toggle="dropdown">
                            <i class="mdi mdi-bell mx-0"></i>
                            <span class="count"></span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="notificationDropdown">
                            <p class="mb-0 font-weight-normal float-left dropdown-header">Notifications</p>
                            <a class="dropdown-item">
                                <div class="item-thumbnail">
                                    <div class="item-icon bg-success">
                                        <i class="mdi mdi-information mx-0"></i>
                                    </div>
                                </div>
                                <div class="item-content">
                                    <h6 class="font-weight-normal">Application Error</h6>
                                    <p class="font-weight-light small-text mb-0 text-muted">
                                        Just now
                                    </p>
                                </div>
                            </a>
                            <a class="dropdown-item">
                                <div class="item-thumbnail">
                                    <div class="item-icon bg-warning">
                                        <i class="mdi mdi-settings mx-0"></i>
                                    </div>
                                </div>
                                <div class="item-content">
                                    <h6 class="font-weight-normal">Settings</h6>
                                    <p class="font-weight-light small-text mb-0 text-muted">
                                        Private message
                                    </p>
                                </div>
                            </a>
                            <a class="dropdown-item">
                                <div class="item-thumbnail">
                                    <div class="item-icon bg-info">
                                        <i class="mdi mdi-account-box mx-0"></i>
                                    </div>
                                </div>
                                <div class="item-content">
                                    <h6 class="font-weight-normal">New user registration</h6>
                                    <p class="font-weight-light small-text mb-0 text-muted">
                                        2 days ago
                                    </p>
                                </div>
                            </a>
                        </div>
                    </li>
                    <li class="nav-item nav-profile dropdown">
                        <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown" id="profileDropdown">
                            <img src="~/admin/images/faces/face5.jpg" alt="profile" />
                            <span class="nav-profile-name">Louis Barnett</span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="profileDropdown">
                            <a class="dropdown-item">
                                <i class="mdi mdi-settings text-primary"></i>
                                Settings
                            </a>
                            <a class="dropdown-item">
                                <i class="mdi mdi-logout text-primary"></i>
                                Logout
                            </a>
                        </div>
                    </li>
                </ul>
                <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
                    <span class="mdi mdi-menu"></span>
                </button>
            </div>
        </nav>
        <!-- partial -->
        <div class="container-fluid page-body-wrapper">
            <!-- partial:partials/_sidebar.html -->
            <nav class="sidebar sidebar-offcanvas" id="sidebar">
                <ul class="nav">
                    <li class="nav-item">
                        <a class="nav-link" asp-action="Index" asp-controller="Home">
                            <i class="mdi mdi-home menu-icon"></i>
                            <span class="menu-title">Dashboard</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" data-bs-toggle="collapse" href="#ui-basic" aria-expanded="false" aria-controls="ui-basic">
                            <i class="mdi mdi-circle-outline menu-icon"></i>
                            <span class="menu-title">UI Elements</span>
                            <i class="menu-arrow"></i>
                        </a>
                        <div class="collapse" id="ui-basic">
                            <ul class="nav flex-column sub-menu">
                                <li class="nav-item"> <a class="nav-link" asp-action="Index" asp-controller="Chef">Chefs</a></li>
                                <li class="nav-item"> <a class="nav-link" asp-action="Index" asp-controller="Settings">Settings</a></li>
                                <li class="nav-item"> <a class="nav-link" asp-action="Index" asp-controller="Position">Positions</a></li>
                            </ul>
                        </div>
                    </li>
                </ul>
            </nav>
            @RenderBody()
            <!-- partial:partials/_footer.html -->
            
            <!-- partial -->
        </div>
        <!-- main-panel ends -->
    </div>
    <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
    <!-- plugins:js -->
    <script src="~/admin/vendors/base/vendor.bundle.base.js"></script>
    <!-- endinject -->
    <!-- Plugin js for this page-->
    <script src="~/admin/vendors/chart.js/Chart.min.js"></script>
    <script src="~/admin/vendors/datatables.net/jquery.dataTables.js"></script>
    <script src="~/admin/vendors/datatables.net-bs4/dataTables.bootstrap4.js"></script>
    <!-- End plugin js for this page-->
    <!-- inject:js -->
    <script src="~/admin/js/off-canvas.js"></script>
    <script src="~/admin/js/hoverable-collapse.js"></script>
    <script src="~/admin/js/template.js"></script>
    <!-- endinject -->
    <!-- Custom js for this page-->
    <script src="~/admin/js/dashboard.js"></script>
    <script src="~/admin/js/data-table.js"></script>
    <script src="~/admin/js/jquery.dataTables.js"></script>
    <script src="~/admin/js/dataTables.bootstrap4.js"></script>
    <!-- End custom js for this page-->

    <script src="~/admin/js/jquery.cookie.js" type="text/javascript"></script>
</body>

</html>